name: Format

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/format.yml
      - src/**
  pull_request:
    paths:
      - .github/workflows/format.yml
      - src/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
