name: Rust update

on:
  schedule:
    - cron: '42 23 * * 0'
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - uses: actions/checkout@v4

      - run: cargo build --verbose
        shell: bash
